version: "3.9"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx_proxy_cgm
    restart: always
    ports: 
      - "80:80"
      - "443:443"
    volumes: 
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs:ro
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - ./staticfiles:/code/staticfiles:ro  # Monta los archivos estáticos
      - ./media:/code/media:ro             # Monta los archivos de medios
    environment:
      - NGINX_TEMPLATE=/etc/docker-gen/templates/nginx.tmpl
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt_cgm
    restart: always
    volumes:
      - ./certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - nginx-proxy

  web:
    container_name: web_cgm
    restart: always
    build: .
    image: cgm:tag
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             gunicorn djangoCgm.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/code:rw
      - ./staticfiles:/code/staticfiles:rw
      - ./media:/code/media:rw
      - ./.env:/code/.env:ro
    expose:
      - "8000"
    environment:
      - VIRTUAL_HOST=golfmilitar.cl,www.golfmilitar.cl
      - LETSENCRYPT_HOST=golfmilitar.cl,www.golfmilitar.cl
      - LETSENCRYPT_EMAIL=secretario@golfmilitar.cl
      - DEBUG=False
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}

volumes:
  static_volume:
    driver: local
  media_volume:
    driver: local
