version: "3.9"
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx_proxy_cgm
    restart: always
    ports: 
      - "80:80"
      - "443:443"
    volumes: 
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /home/certs:/etc/nginx/certs:ro
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf  # Montar archivo nginx.conf
      - static_volume:/code/staticfiles                  # Montar archivos estáticos
      - media_volume:/code/media                         # Montar archivos de medios
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt_cgm
    restart: always
    volumes:
      - /home/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - nginx-proxy

  web:
    container_name: web_cgm
    restart: always
    build: ./
    image: cgm:tag
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             gunicorn djangoCgm.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/code
      - static_volume:/code/staticfiles
      - media_volume:/code/media
    expose:
      - "8000"
    environment:
      - VIRTUAL_HOST=golfmilitar.cl,www.golfmilitar.cl
      - LETSENCRYPT_HOST=golfmilitar.cl,www.golfmilitar.cl
      - LETSENCRYPT_EMAIL=secretario@golfmilitar.cl
      - DEBUG=False
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - DATABASE_URL=${DATABASE_URL}

volumes:
  static_volume: {}
  media_volume: {}
