# Generated by Django 3.1.7 on 2023-12-14 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cuota',
        ),
        migrations.DeleteModel(
            name='CuotaAnual',
        ),
    ]
