# Generated by Django 3.1.7 on 2023-12-30 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_links_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='links',
            name='url',
            field=models.CharField(default='#', max_length=500),
        ),
    ]
