# Generated by Django 3.1.7 on 2024-01-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_links_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='links',
            options={'ordering': ['tipo', 'order'], 'verbose_name': 'Link', 'verbose_name_plural': 'Links'},
        ),
        migrations.AddField(
            model_name='links',
            name='banner',
            field=models.BooleanField(default=False),
        ),
    ]
