# Generated by Django 3.1.7 on 2024-01-18 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20240105_1254'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listado',
            options={'ordering': ['grupo', 'tipo'], 'verbose_name': 'Listado', 'verbose_name_plural': 'Listados'},
        ),
        migrations.AddField(
            model_name='listado',
            name='grupo',
            field=models.CharField(choices=[('M', 'Miembros'), ('D', 'Directores')], default='M', max_length=20),
        ),
    ]
