# Generated by Django 3.1.7 on 2024-04-10 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20240118_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campeonato',
            name='club',
        ),
        migrations.DeleteModel(
            name='NormaRegla',
        ),
        migrations.DeleteModel(
            name='Campeonato',
        ),
        migrations.DeleteModel(
            name='Club',
        ),
    ]
