# Generated by Django 3.1.7 on 2024-04-10 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_paginas_web'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Front',
        ),
    ]
