# Generated by Django 3.1.7 on 2024-04-11 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_delete_front'),
    ]

    operations = [
        migrations.AddField(
            model_name='paginas_web',
            name='tipo',
            field=models.CharField(choices=[('H', 'Historia'), ('D', 'Directorio'), ('E', 'Estatutos'), ('404', '404')], default='H', max_length=20),
        ),
        migrations.AddField(
            model_name='paginas_web',
            name='tituloPestana',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
