# Generated by Django 3.1.7 on 2024-04-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_auto_20240411_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paginas_web',
            name='tipo',
            field=models.CharField(choices=[('H', 'Historia'), ('D', 'Directorio'), ('E', 'Estatutos'), ('C', 'Comite'), ('404', '404')], default='H', max_length=20),
        ),
    ]
