# Generated by Django 3.1.7 on 2023-12-04 00:32

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0006_auto_20231204_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torneo',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from=['titulo', 'fecha'], unique_with=['titulo', 'fecha']),
        ),
    ]
