# Generated by Django 3.1.7 on 2023-12-04 00:39

import autoslug.fields
from django.db import migrations
import socios.models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0007_auto_20231204_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torneo',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from=socios.models.slugify_two_fields, unique_with=['titulo', 'fecha']),
        ),
    ]
