# Generated by Django 3.1.7 on 2023-12-04 00:51

import autoslug.fields
from django.db import migrations
import socios.models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0008_auto_20231204_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from=socios.models.slugify_two_fields, unique_with=['titulo', 'fecha']),
        ),
    ]
