# Generated by Django 3.1.7 on 2023-12-04 01:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socios', '0009_auto_20231204_0051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('busCGM', models.BooleanField(default=False)),
                ('carro', models.BooleanField(default=False)),
                ('indice', models.IntegerField(blank=True, null=True, verbose_name='Indice')),
                ('acompanantes', models.TextField(blank=True, verbose_name='¿Con quién va?')),
                ('descripcion', models.TextField(blank=True, verbose_name='Solicitud')),
                ('deuda_socio', models.IntegerField(default=0, verbose_name='Deuda Socio')),
                ('recargo', models.IntegerField(default=0, verbose_name='Recargo')),
                ('cuota', models.IntegerField(default=0, verbose_name='Cuota de Campeonato')),
                ('torneo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='socios.torneo', verbose_name='Torneo')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
                'ordering': ['-fecha'],
            },
        ),
    ]
