# Generated by Django 3.1.7 on 2023-12-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0011_auto_20231204_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneo',
            name='bases',
            field=models.FileField(blank=True, max_length=254, upload_to='torneos/bases/'),
        ),
        migrations.AddField(
            model_name='torneo',
            name='premiacion',
            field=models.FileField(blank=True, max_length=254, upload_to='torneos/premiacion/'),
        ),
        migrations.AddField(
            model_name='torneo',
            name='resultados',
            field=models.FileField(blank=True, max_length=254, upload_to='torneos/resultados/'),
        ),
    ]
