# Generated by Django 3.1.7 on 2023-12-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0013_solicitud_monto'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='cancela_deuda_socio',
            field=models.BooleanField(default=False),
        ),
    ]
