# Generated by Django 3.1.7 on 2023-12-08 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0014_solicitud_cancela_deuda_socio'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='hoyoInicial',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Hoyo Inicial'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='indiceTorneo',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Indice Torneo'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(choices=[('P', 'Pendiente'), ('A', 'Aprobado'), ('R', 'Rechazado'), ('S', 'Suspender')], default='P', max_length=50, verbose_name='Estado'),
        ),
    ]
