# Generated by Django 3.1.7 on 2023-12-08 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0015_auto_20231208_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='motivoSuspencion',
            field=models.TextField(blank=True, default='', verbose_name='Motivo Suspención'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='suspende',
            field=models.BooleanField(default=False, verbose_name='Suspende Participación'),
        ),
    ]
