# Generated by Django 3.1.7 on 2023-12-08 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0016_auto_20231208_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='checkCapitan',
            field=models.BooleanField(default=False),
        ),
    ]
