# Generated by Django 3.1.7 on 2023-12-09 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0017_solicitud_checkcapitan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
