# Generated by Django 3.1.7 on 2023-12-14 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socios', '0018_auto_20231209_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuotaAnual',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('año', models.PositiveIntegerField(verbose_name='Año cuotas')),
                ('monto_cuota', models.IntegerField()),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'CuotaAnual',
                'verbose_name_plural': 'CuotasAnuales',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mes', models.IntegerField()),
                ('monto_descuento', models.PositiveIntegerField(blank=True, null=True)),
                ('monto_cargo', models.PositiveIntegerField(blank=True, null=True)),
                ('monto_pago', models.PositiveIntegerField(blank=True, null=True)),
                ('fecha_pago', models.DateField(blank=True, null=True, verbose_name='Fecha de pago')),
                ('estado_pago', models.CharField(choices=[('P', 'Pendiente'), ('C', 'Cancelado')], default='P', max_length=1, verbose_name='Estado de la cuota')),
                ('order', models.IntegerField(default=0)),
                ('año', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='socios.cuotaanual')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='socio club')),
            ],
            options={
                'verbose_name': 'Cuota',
                'verbose_name_plural': 'Cuotas',
                'ordering': ['año', 'mes'],
            },
        ),
    ]
