# Generated by Django 3.1.7 on 2023-12-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0019_cuota_cuotaanual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuota',
            name='estado_pago',
            field=models.CharField(choices=[('P', 'Pendiente'), ('E', 'En Revision'), ('A', 'Aprobada'), ('R', 'Rechazada')], default='P', max_length=1, verbose_name='Estado de la cuota'),
        ),
    ]
