# Generated by Django 3.1.7 on 2023-12-29 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0020_auto_20231229_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='auto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='patente',
            field=models.CharField(blank=True, max_length=12, verbose_name='Patente'),
        ),
    ]
