# Generated by Django 3.1.7 on 2024-01-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0022_torneo_list_inscritos'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='recargoInvitado',
            field=models.IntegerField(default=0, verbose_name='Recargo Invitado'),
        ),
    ]
