# Generated by Django 4.2.7 on 2024-01-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0023_solicitud_recargoinvitado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuota',
            options={'ordering': ['año', 'order'], 'verbose_name': 'Cuota', 'verbose_name_plural': 'Cuotas'},
        ),
        migrations.AddField(
            model_name='cuota',
            name='numero_cuota',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cuotaanual',
            name='periodo',
            field=models.CharField(default=12, max_length=50, verbose_name='Periodo'),
            preserve_default=False,
        ),
    ]
