# Generated by Django 4.2.7 on 2024-01-30 17:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0024_alter_cuota_options_cuota_numero_cuota_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoCuota',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('monto_cargo', models.PositiveIntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'CargoCuota',
                'verbose_name_plural': 'CargoCuotas',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DescuentoCuota',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('monto_descuento', models.PositiveIntegerField(blank=True, null=True)),
                ('descuento_activo', models.BooleanField(default=False, verbose_name='activo')),
                ('periodo_des_inicio', models.IntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], default=3)),
                ('periodo_des_fin', models.IntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], default=3)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'DescuentoCuota',
                'verbose_name_plural': 'DescuentoCuotas',
                'ordering': ['order'],
            },
        ),
        migrations.RemoveField(
            model_name='cuota',
            name='monto_cargo',
        ),
        migrations.RemoveField(
            model_name='cuota',
            name='monto_descuento',
        ),
        migrations.AlterField(
            model_name='cuota',
            name='monto_pago',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Monto total a pagar'),
        ),
        migrations.AlterField(
            model_name='cuotaanual',
            name='monto_cuota',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cuotaanual',
            name='cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='socios.cargocuota'),
        ),
        migrations.AddField(
            model_name='cuotaanual',
            name='descuento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='socios.descuentocuota'),
        ),
    ]
