# Generated by Django 3.1.7 on 2024-02-06 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0025_cargocuota_descuentocuota_remove_cuota_monto_cargo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='is_aprobado',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='is_pendiente',
        ),
    ]
