# Generated by Django 3.1.7 on 2024-02-06 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0026_auto_20240206_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='comentario',
        ),
    ]
