# Generated by Django 3.1.7 on 2024-02-06 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0027_remove_noticia_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='img',
            field=models.ImageField(blank=True, upload_to='noticias/'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
