# Generated by Django 3.1.7 on 2024-02-23 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0028_auto_20240206_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuotaanual',
            name='descuento_activo',
            field=models.BooleanField(default=False, verbose_name='activo'),
        ),
        migrations.AddField(
            model_name='cuotaanual',
            name='periodo_des_fin',
            field=models.IntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], default=3),
        ),
        migrations.AddField(
            model_name='cuotaanual',
            name='periodo_des_inicio',
            field=models.IntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], default=3),
        ),
        migrations.AlterField(
            model_name='cuotaanual',
            name='cargo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cuotaanual',
            name='descuento',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='CargoCuota',
        ),
        migrations.DeleteModel(
            name='DescuentoCuota',
        ),
    ]
