# Generated by Django 3.1.7 on 2024-03-07 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0029_auto_20240222_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(blank=True, choices=[('P', 'Pendiente'), ('A', 'Aprobado'), ('R', 'Rechazado'), ('S', 'Suspender')], default='P', max_length=50, verbose_name='Estado'),
        ),
    ]
