# Generated by Django 3.1.7 on 2024-04-08 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0030_auto_20240307_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='torneo',
            name='img',
        ),
        migrations.AddField(
            model_name='torneo',
            name='list_salidas',
            field=models.FileField(blank=True, max_length=254, upload_to='torneos/salidas/', verbose_name='Listado de Salidas'),
        ),
    ]
