# Generated by Django 3.1.7 on 2024-04-10 12:32

import autoslug.fields
from django.db import migrations, models
import socios.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0032_auto_20240410_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Multimedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('fecha', models.DateField()),
                ('info', models.TextField()),
                ('img', models.FileField(upload_to='multimedia')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=socios.models.slugify_two_fields, unique_with=['titulo', 'fecha'])),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Multimedia',
                'verbose_name_plural': 'Multimedias',
                'ordering': ['-fecha'],
            },
        ),
    ]
