# Generated by Django 3.1.7 on 2024-04-10 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0035_paginas_socio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paginas_socio',
            options={'ordering': ['titulo'], 'verbose_name': 'Paginas_Socio', 'verbose_name_plural': 'Paginas_Socios'},
        ),
        migrations.RemoveField(
            model_name='paginas_socio',
            name='order',
        ),
    ]
