# Generated by Django 3.1.7 on 2024-04-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0038_auto_20240415_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardsinicio',
            name='img',
            field=models.ImageField(upload_to='CardsInicio/'),
        ),
    ]
