# Generated by Django 3.1.7 on 2024-04-17 10:56

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0043_auto_20240417_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='cuota',
            field=djmoney.models.fields.MoneyField(decimal_places=0, default=Decimal('0'), default_currency='CLP', max_digits=11, verbose_name='Cuota de Campeonato'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='deuda_socio',
            field=djmoney.models.fields.MoneyField(decimal_places=0, default=Decimal('0'), default_currency='CLP', max_digits=11, verbose_name='Deuda Socio'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='monto',
            field=djmoney.models.fields.MoneyField(decimal_places=0, default=Decimal('0'), default_currency='CLP', max_digits=11, verbose_name='Monto Pagado'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='recargo',
            field=djmoney.models.fields.MoneyField(decimal_places=0, default=Decimal('0'), default_currency='CLP', max_digits=11, verbose_name='Recargo'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='recargoInvitado',
            field=djmoney.models.fields.MoneyField(decimal_places=0, default=Decimal('0'), default_currency='CLP', max_digits=11, verbose_name='Recargo Invitado'),
        ),
    ]
