# Generated by Django 3.1.7 on 2024-04-17 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0044_auto_20240417_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='cuota_currency',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='deuda_socio_currency',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='monto_currency',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='recargoInvitado_currency',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='recargo_currency',
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='cuota',
            field=models.PositiveIntegerField(default=0, verbose_name='Cuota de Campeonato'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='deuda_socio',
            field=models.PositiveIntegerField(default=0, verbose_name='Deuda Socio'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='monto',
            field=models.PositiveIntegerField(default=0, verbose_name='Monto Pagado'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='recargo',
            field=models.PositiveIntegerField(default=0, verbose_name='Recargo'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='recargoInvitado',
            field=models.PositiveIntegerField(default=0, verbose_name='Recargo Invitado'),
        ),
    ]
