# Generated by Django 3.1.7 on 2024-04-27 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0045_auto_20240417_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='motivo',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='motivoSuspencion',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='suspende',
        ),
        migrations.AlterField(
            model_name='paginas_socio',
            name='tipo',
            field=models.CharField(choices=[('B', 'Bus'), ('E', 'Estacionamiento'), ('Ca', 'Carro'), ('Cump', 'Cumpleaños'), ('C', 'Cuotas'), ('S', 'Salida'), ('R', 'Ranking'), ('CALEN', 'Calendario'), ('Noti', 'Noticias'), ('Multi', 'Multimedia')], default='B', max_length=20),
        ),
    ]
