# Generated by Django 3.1.7 on 2024-04-28 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0046_auto_20240427_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='estado',
        ),
    ]
