# Generated by Django 3.1.7 on 2024-04-28 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0047_remove_solicitud_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='noticias/')),
            ],
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='img1',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='img3',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='img4',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='img5',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='img',
        ),
        migrations.AddField(
            model_name='noticia',
            name='img',
            field=models.ManyToManyField(blank=True, to='socios.Image'),
        ),
    ]
