# Generated by Django 3.1.7 on 2024-04-28 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0048_auto_20240428_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='img',
        ),
        migrations.AddField(
            model_name='noticia',
            name='img',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='NoticiaImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(upload_to='noticias/')),
                ('noticia', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='socios.noticia')),
            ],
            options={
                'verbose_name': 'NoticiaImg',
                'verbose_name_plural': 'NoticiasImg',
                'ordering': ['img'],
            },
        ),
    ]
