# Generated by Django 3.1.7 on 2024-04-28 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0049_auto_20240428_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='img',
        ),
    ]
