# Generated by Django 3.1.7 on 2024-04-28 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0051_auto_20240428_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='img',
            field=models.ImageField(blank=True, upload_to='noticias/', verbose_name='Imagen Principal'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='fecha',
            field=models.DateField(),
        ),
    ]
