# Generated by Django 3.1.7 on 2024-04-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0052_auto_20240428_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='img',
            field=models.ImageField(upload_to='noticias/', verbose_name='Imagen Principal'),
        ),
    ]
