# Generated by Django 3.1.7 on 2024-05-11 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0056_remove_torneo_list_inscritos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuota',
            name='numero_cuota',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='paginas_socio',
            name='tipo',
            field=models.CharField(choices=[('B', 'Bus'), ('E', 'Estacionamiento'), ('Ca', 'Carro'), ('Cump', 'Cumpleaños'), ('C', 'Cuotas'), ('S', 'Salida'), ('R', 'Ranking'), ('CALEN', 'Calendario'), ('Noti', 'Noticias'), ('Multi', 'Multimedia'), ('Ins', 'Inscritos')], default='B', max_length=20),
        ),
    ]
