# Generated by Django 3.1.7 on 2024-05-15 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0059_torneo_recargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='detalleCuotasPagadas',
            field=models.TextField(default='[]', verbose_name='Detalle cuotas Pagadas'),
        ),
    ]
