# Generated by Django 3.1.7 on 2024-05-17 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0060_solicitud_detallecuotaspagadas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='detalleCuotasPagadas',
        ),
        migrations.AddField(
            model_name='solicitud',
            name='detalle_cuotas_pagadas',
            field=models.TextField(default='', verbose_name='Detalle cuotas Pagadas'),
        ),
    ]
