# Generated by Django 3.1.7 on 2024-09-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0061_auto_20240517_2319'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuota',
            options={'ordering': ['usuario__rut', 'año', 'numero_cuota'], 'verbose_name': 'Cuota', 'verbose_name_plural': 'Cuotas'},
        ),
        migrations.AddField(
            model_name='torneo',
            name='ticket_inv',
            field=models.IntegerField(default=7000, verbose_name='Ticket Invitado'),
        ),
        migrations.AlterField(
            model_name='cuota',
            name='estado_pago',
            field=models.CharField(choices=[('P', 'Pendiente'), ('A', 'Aprobada')], default='P', max_length=1, verbose_name='Estado de la cuota'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='detalle_cuotas_pagadas',
            field=models.TextField(default='[]', verbose_name='Detalle cuotas Pendientes'),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='recargo',
            field=models.IntegerField(default=5000, verbose_name='Multa Socio'),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='ticket',
            field=models.IntegerField(default=7000, verbose_name='Ticket Socio'),
        ),
    ]
