# Generated by Django 3.1.7 on 2024-09-03 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0062_auto_20240903_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='recargo',
            field=models.PositiveIntegerField(default=0, verbose_name='Recargo Socio'),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='recargo',
            field=models.IntegerField(default=5000, verbose_name='Recargo Socio'),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='ticket',
            field=models.IntegerField(default=7000, verbose_name='Ticket Campeonato'),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='ticket_inv',
            field=models.IntegerField(default=8000, verbose_name='Recargo Invitado'),
        ),
    ]
