# Generated by Django 3.1.7 on 2024-09-03 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0063_auto_20240903_1523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitud',
            old_name='recargoInvitado',
            new_name='recargo_invitado',
        ),
    ]
