# Generated by Django 3.1.7 on 2024-09-10 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0064_auto_20240903_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='caddy',
            field=models.BooleanField(default=False),
        ),
    ]
