# Generated by Django 3.1.7 on 2024-09-13 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0065_solicitud_caddy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='caddy',
        ),
        migrations.AlterField(
            model_name='paginas_socio',
            name='tipo',
            field=models.CharField(choices=[('B', 'Bus'), ('E', 'Estacionamiento'), ('Ca', 'Carro'), ('Caddy', 'Caddy'), ('Cump', 'Cumpleaños'), ('C', 'Cuotas'), ('S', 'Salida'), ('R', 'Ranking'), ('CALEN', 'Calendario'), ('Noti', 'Noticias'), ('Multi', 'Multimedia'), ('Ins', 'Inscritos')], default='B', max_length=20),
        ),
    ]
