# Generated by Django 3.1.7 on 2024-09-23 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0067_parametro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='region',
            field=models.CharField(choices=[('XIII', 'Región Metropolitana de Santiago'), ('I', 'Región de Tarapacá'), ('II', 'Región de Antofagasta'), ('III', 'Región de Atacama'), ('IV', 'Región de Coquimbo'), ('V', 'Región de Valparaíso'), ('VI', 'Región del Libertador General Bernardo O’Higgins'), ('VII', 'Región del Maule'), ('VIII', 'Región del Bio-bío'), ('IX', 'Región de La Araucanía'), ('X', 'Región de Los Lagos'), ('XI', 'Región Aysén del General Carlos Ibáñez del Campo'), ('XII', 'Región de Magallanes y Antártica Chilena'), ('XIV', 'Región de Los Ríos'), ('XV', 'Región de Arica y Parinacota'), ('XVI', 'Región de Ñuble'), ('NI', 'NO INFORMAR')], default='XIII', max_length=50, verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='region',
            field=models.CharField(choices=[('XIII', 'Región Metropolitana de Santiago'), ('I', 'Región de Tarapacá'), ('II', 'Región de Antofagasta'), ('III', 'Región de Atacama'), ('IV', 'Región de Coquimbo'), ('V', 'Región de Valparaíso'), ('VI', 'Región del Libertador General Bernardo O’Higgins'), ('VII', 'Región del Maule'), ('VIII', 'Región del Bio-bío'), ('IX', 'Región de La Araucanía'), ('X', 'Región de Los Lagos'), ('XI', 'Región Aysén del General Carlos Ibáñez del Campo'), ('XII', 'Región de Magallanes y Antártica Chilena'), ('XIV', 'Región de Los Ríos'), ('XV', 'Región de Arica y Parinacota'), ('XVI', 'Región de Ñuble'), ('NI', 'NO INFORMAR')], default='XIII', max_length=50, verbose_name='Region'),
        ),
    ]
