# Generated by Django 3.1.7 on 2024-10-02 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0068_auto_20240923_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneo',
            name='ticket_bus',
            field=models.IntegerField(default=10000, verbose_name='Ticket Bus'),
        ),
    ]
