# Generated by Django 3.1.7 on 2024-10-02 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0069_torneo_ticket_bus'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='recargo_bus',
            field=models.PositiveIntegerField(default=0, verbose_name='Recargo Bus'),
        ),
    ]
