# Generated by Django 3.1.7 on 2024-10-02 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0070_solicitud_recargo_bus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='indice',
            field=models.CharField(blank=True, default='', max_length=12, verbose_name='Indice'),
        ),
    ]
