# Generated by Django 3.1.7 on 2023-12-03 23:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('perfil', models.CharField(max_length=30, verbose_name='Perfil de usuario')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripcion del perfil')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email')),
                ('date_of_birth', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('rut', models.CharField(blank=True, max_length=10, verbose_name='Rut')),
                ('primer_nombre', models.CharField(blank=True, max_length=200, verbose_name='Primer nombre')),
                ('segundo_nombre', models.CharField(blank=True, max_length=200, verbose_name='Segundo nombre')),
                ('apellido_paterno', models.CharField(blank=True, max_length=200, verbose_name='Apellido paterno')),
                ('apellido_materno', models.CharField(blank=True, max_length=200, verbose_name='Apellido materno')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('telefono', models.IntegerField(blank=True, null=True, verbose_name='Telefono movil')),
                ('sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='M', max_length=1)),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo'), ('S', 'Suspendido')], default='A', max_length=1)),
                ('perfil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfil', verbose_name='Perfil de usuario')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
