# Generated by Django 3.1.7 on 2023-12-04 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='categoria',
            field=models.CharField(choices=[('E', 'Experto'), ('M', 'Media'), ('N', 'Novato')], default='N', max_length=1),
        ),
    ]
