# Generated by Django 3.1.7 on 2023-12-29 12:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='condicion',
            field=models.CharField(choices=[('R', 'RETIRO'), ('A', 'ACTIVO'), ('NI', 'NO INFORMAR')], default='NI', max_length=20),
        ),
        migrations.AddField(
            model_name='usuario',
            name='eCivil',
            field=models.CharField(choices=[('S', 'SOLTERO'), ('C', 'CASADO'), ('V', 'VIUDO'), ('D', 'DIVORCIADO'), ('CCIVL', 'CONVIVIENTE CIVIL')], default='S', max_length=30, verbose_name='Estado Civil'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_incorporacion',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fundador',
            field=models.BooleanField(default=False, verbose_name='Fundador'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='grado',
            field=models.CharField(choices=[('GDB', 'GENERAL DE BRIGADA'), ('CRL', 'CORONEL'), ('TCL', 'TENIENTE CORONEL'), ('CAD', 'CAD'), ('NI', 'NO INFORMAR')], default='NI', max_length=5),
        ),
        migrations.AddField(
            model_name='usuario',
            name='instituciOn',
            field=models.CharField(choices=[('E', 'Ejército'), ('A', 'Armada'), ('FACH', 'Fuerza Aérea'), ('C', 'Carabineros'), ('PDI', 'PDI'), ('NI', 'NO INFORMAR')], default='NI', max_length=20),
        ),
        migrations.AddField(
            model_name='usuario',
            name='profesion',
            field=models.CharField(blank=True, max_length=200, verbose_name='Profesión'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='situacionEspecial',
            field=models.BooleanField(default=False, verbose_name='Situación Especial'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='categoria',
            field=models.CharField(choices=[('S', 'SENIOR'), ('SS', 'SUPER SENIOR'), ('V', 'VARON'), ('J', 'JUVENIL')], default='N', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='estado',
            field=models.CharField(choices=[('A', 'ACTIVO'), ('H', 'HONORARIO'), ('C', 'COOPERADOR'), ('PCS', 'PERDIDA CATEGORIA SOCIO'), ('S', 'SUSPENDIDO')], default='A', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='sexo',
            field=models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='M', max_length=1, verbose_name='Genero'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.IntegerField(blank=True, null=True, verbose_name='Celular'),
        ),
    ]
