# Generated by Django 3.1.7 on 2023-12-29 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_remove_usuario_date_of_birth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='instituciOn',
            new_name='institucion',
        ),
    ]
