# Generated by Django 3.1.7 on 2024-02-20 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_auto_20240220_1029'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
