# Generated by Django 3.1.7 on 2024-03-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_auto_20240305_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=255, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='profesion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Profesión'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='segundo_nombre',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Segundo nombre'),
        ),
    ]
