# Generated by Django 3.1.7 on 2024-03-05 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_auto_20240305_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fecha_incorporacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de incorporacion'),
        ),
    ]
