# Generated by Django 3.1.7 on 2024-03-05 11:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0014_auto_20240305_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fecha_incorporacion',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Fecha de nacimiento'),
        ),
    ]
