# Generated by Django 3.1.7 on 2024-03-05 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0015_auto_20240305_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='grado',
            field=models.CharField(choices=[('GDB', 'GENERAL DE BRIGADA'), ('CRL', 'CORONEL'), ('TCL', 'TENIENTE CORONEL'), ('CAD', 'CADETE '), ('NI', 'NO INFORMAR')], default='NI', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='institucion',
            field=models.CharField(choices=[('E', 'Ejército'), ('A', 'Armada'), ('FACH', 'Fuerza Aérea'), ('C', 'Carabineros'), ('PDI', 'PDI'), ('NI', 'NO INFORMAR')], default='NI', max_length=20, null=True),
        ),
    ]
