# Generated by Django 3.1.7 on 2024-03-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0016_auto_20240305_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='grado',
            field=models.CharField(blank=True, choices=[('GDB', 'GENERAL DE BRIGADA'), ('CRL', 'CORONEL'), ('TCL', 'TENIENTE CORONEL'), ('CAD', 'CADETE '), ('NI', 'NO INFORMAR')], default='NI', max_length=5),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='institucion',
            field=models.CharField(blank=True, choices=[('E', 'Ejército'), ('A', 'Armada'), ('FACH', 'Fuerza Aérea'), ('C', 'Carabineros'), ('PDI', 'PDI'), ('NI', 'NO INFORMAR')], default='NI', max_length=20),
        ),
    ]
