# Generated by Django 3.1.7 on 2024-09-09 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0019_auto_20240417_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tiempoGracia',
            field=models.IntegerField(default=30, verbose_name='Tiempo Gracia'),
        ),
    ]
