# Generated by Django 3.1.7 on 2024-09-09 19:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0020_usuario_tiempogracia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fecha_incorporacion',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Fecha de incorporacion'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Celular'),
        ),
    ]
