# Generated by Django 3.1.7 on 2024-09-16 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0021_auto_20240909_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='perfil',
            field=models.CharField(choices=[('S', 'Socio'), ('S_V', 'Socio Vitalicio'), ('S_E', 'Socio Especial'), ('I', 'Invitado'), ('I_E', 'Invitado Especial'), ('T', 'Tesorero'), ('SECR', 'Secretario'), ('CAP', 'Capitan'), ('SUPER', 'Super Usuario')], default='S', max_length=20),
        ),
    ]
