# Generated by Django 3.1.7 on 2024-09-23 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0024_usuario_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='number',
            field=models.PositiveIntegerField(default=0, verbose_name='Numero'),
        ),
    ]
