# Generated by Django 3.1.7 on 2024-09-23 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0025_usuario_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='number',
        ),
    ]
