# Generated by Django 3.1.7 on 2024-10-02 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0026_remove_usuario_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='estado',
            field=models.CharField(choices=[('A', 'ACTIVO'), ('H', 'HONORARIO'), ('C', 'COOPERADOR'), ('PCS', 'PERDIDA CATEGORIA SOCIO'), ('S', 'SUSPENDIDO'), ('F', 'FALLECIDO')], default='A', max_length=20),
        ),
    ]
